### ISSUE TITLE
Parodyti visus tripus

### ISSUE THREAD

**Issue by joklek** [uzspringom-javainiais/front-end#10]

**Comment by Adomas202** [comment]
Tripus jau fronte rodo, reikia dar prideti backende datas i modeli

**Comment by taskiukas** [comment]
@Adomas202 
reikia padaryti du langus: Mano keliones, Visos keliones(mato tik adminas). Su adomu tai aptarem.

**Comment by Adomas202** [comment]
In progress

**Comment by Adomas202** [comment]
Kaip ir done, nebent, kaip minėjau padarytumėme kažką patogesnio :D
