### ISSUE TITLE
Sukurti tripą

### ISSUE THREAD

**Issue by joklek** [uzspringom-javainiais/front-end#9]
Parsipulint userius, kada jie galimi, checklist itemus

**Comment by Adomas202** [comment]
Jau tripo sukurimas veikia, dar tik backe reikia prideti datu saugojima ir turim issiakinti kuo skiriasi itemai nuo trip stepsu

**Comment by taskiukas** [comment]
teliko implementuoti backe tripo kurejo priskyrima kelionei (organizer). 
padarysiu.

**Comment by taskiukas** [comment]
done

**Comment by taskiukas** [comment]
wow. such automations
